export { default as IconBrandRecognition } from './IconBrandRecognition'
export { default as IconDetailedRecords } from './IconDetailedRecords'
export { default as IconFacebook } from './IconFacebook'
export { default as IconFullyCustomizable } from './IconFullyCustomizable'
export { default as IconInstagram } from './IconInstagram'
export { default as IconPinterest } from './IconPinterest'
export { default as IconTwitter } from './IconTwitter'
export { default as Logo } from './Logo'
